# Generated by Django 5.1.3 on 2024-11-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_userorganization_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='origanisation',
            new_name='organisation',
        ),
    ]
